name: Gold Crest Holidays
favicon: null
layout_spectrum: 0.17687660013325512
typography_spectrum: 0.1959046022966504
title: 'Short Breaks by Coach, Air and River Cruises'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8929112607147545
  lightness: 0.542926927562803
  saturation: 0.44105942687019706
  rhythmicContrast: 0.816925706109032
purpose: []
