name: Gold Crest Holidays
favicon: null
layout_spectrum: 0.98427
typography_spectrum: 0.63559
title: 'Short Breaks by Coach, Air and River Cruises'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fef625'
    - '#747cbb'
    - '#1d2a8f'
    - '#e75a2a'
  brandStrength: 0.8929112607147545
  lightness: 0.542926927562803
  saturation: 0.44105942687019706
  rhythmicContrast: 0.816925706109032
purpose: []
